HSE = 25e6 / 3; % HSE from stlink
pll2m = 4;
pll2n = 280;
pll2p = 8;
F_spi = HSE / pll2m * pll2n / pll2p / 2;
Ts = 16 / F_spi;
fc = 50e3;
n = 4;
[zb,pb,kb] = butter(n,2*pi*fc,'s');
[bb,ab] = zp2tf(zb,pb,kb);
[hb,wb] = freqs(bb,ab,4096);

figure
plot(wb/(2*pi),mag2db(abs(hb)))
hold on
axis([0 300e3 -40 5])
grid
xlabel('Frequency (Hz)')
ylabel('Attenuation (dB)')
legend('butter')

Gp = tf(bb, ab);
figure;
bode(Gp);

Gcz = c2d(Gp, Ts, 'tustin');
Gcz.variable='z^-1';
cn = Gcz.Numerator{1};
cd = Gcz.Denominator{1};
format long
% fprintf(strcat("yi[j] = (%.10e) * aRxBuffer[j] + (%.10e) * aRxBuffer[j-1] \\\n", ...
% "+ (%.10e) * aRxBuffer[j-2] + (%.10e) * aRxBuffer[j-3] \\\n", ...
% "+ (%.10e) * aRxBuffer[j-4] + (%.10e) * aRxBuffer[j-5] \\\n", ...
% "- (%.10e) * yi[j-1] - (%.10e) * yi[j-2] \\\n", ...
% "- (%.10e) * yi[j-3] - (%.10e) * yi[j-4] \\\n", ...
% "- (%.10e) * yi[j-5];\n\n"), cn(1), cn(2), cn(3), cn(4), cn(5), cn(6), ...
%     cd(2), cd(3), cd(4), cd(5), cd(6));

fprintf(strcat("yi[j] = (%.10e) * aRxBuffer[j] + (%.10e) * aRxBuffer[j-1] \\\n", ...
"+ (%.10e) * aRxBuffer[j-2] + (%.10e) * aRxBuffer[j-3] \\\n", ...
"+ (%.10e) * aRxBuffer[j-4] \\\n", ...
"- (%.10e) * yi[j-1] - (%.10e) * yi[j-2] \\\n", ...
"- (%.10e) * yi[j-3] - (%.10e) * yi[j-4];\n\n"), cn(1), cn(2), cn(3), cn(4), cn(5), ...
    cd(2), cd(3), cd(4), cd(5));

% fprintf(strcat("yi[j] = (%.10e) * aRxBuffer[j] + (%.10e) * aRxBuffer[j-1] \\\n", ...
% "+ (%.10e) * aRxBuffer[j-2] + (%.10e) * aRxBuffer[j-3] \\\n", ...
% "- (%.10e) * yi[j-1] - (%.10e) * yi[j-2] \\\n", ...
% "- (%.10e) * yi[j-3];\n\n"), cn(1), cn(2), cn(3), cn(4), ...
%     cd(2), cd(3), cd(4));

% fprintf(strcat("yi[j] = (%.10e) * aRxBuffer[j] + (%.10e) * aRxBuffer[j-1] \\\n", ...
% "+ (%.10e) * aRxBuffer[j-2] \\\n", ...
% "- (%.10e) * yi[j-1] - (%.10e) * yi[j-2];\n\n"), cn(1), cn(2), cn(3), ...
%     cd(2), cd(3));

% fprintf(strcat("yi[j] = (%.10e) * aRxBuffer[j] + (%.10e) * aRxBuffer[j-1] \\\n", ...
% "- (%.10e) * yi[j-1];\n\n"), cn(1), cn(2), ...
%     cd(2));